# SPDX-FileCopyrightText: 2026 Wojciech Polak
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generated by scripts/render-homebrew-formula in wojciechpolak/clocwork and
# rewritten in full by that repository's release workflow. Edit the renderer,
# not this file.

class Clocwork < Formula
  include Language::Python::Virtualenv

  desc "Aggregate cloc line counts across several projects into one report"
  homepage "https://github.com/wojciechpolak/clocwork"
  url "https://github.com/wojciechpolak/clocwork/releases/download/v0.9.0/clocwork-0.9.0-py3-none-any.whl", using: :nounzip
  sha256 "a6c5ecea08c306d737f4401094aa2d50a3a5052de087988fbfd94a6b25f616b4"
  license "GPL-3.0-or-later"

  depends_on "cloc"
  depends_on "git"
  depends_on "python@3.14"

  def install
    venv = virtualenv_create(libexec, "python3.14")
    venv.pip_install_and_link buildpath/"clocwork-#{version}-py3-none-any.whl"
  end

  test do
    reported = shell_output("#{bin}/clocwork --version").strip
    assert_equal "clocwork #{version}", reported

    (testpath/"src").mkpath
    (testpath/"src/hello.py").write "print('hi')\n"
    config = testpath/"projects.toml"
    config.write <<~TOML
      [defaults]
      root = "."
      vcs = "none"

      [[project]]
      repo = "src"
      name = "Sample"
    TOML

    output = shell_output("#{bin}/clocwork --quiet --config #{config} --stdout txt")
    assert_match "Python", output
    assert_match "Sample", output
  end
end
